apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caasperli
  namespace: infra-argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.adfinis.com
    chart: caasperli
    targetRevision: '*'
